### ISSUE TITLE
Enable Object: URDF doesn't show anything.

### ISSUE THREAD

**Issue by benthebear93** [mcevoyandy/blender_urdf_visualizer#2]
My blender version : 2.93.4, Window

I followed your steps.

put "blender_urdf_visualizer-min" or "blender_urdf_visualizer"  in 
C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons_contrib

and Opend Blender to Enable Object: URDF

But this doesn't show anything on my blender.

![add_on](https://user-images.githubusercontent.com/34788458/136150474-ea38e087-abe6-4710-87f9-272c76d753f4.JPG)
Did i miss some steps?

**Comment by mcevoyandy** [comment]
Could you show more of your screen. Once the plugin is activated, the controls should show up as in this gif:

![blender_urdf_viz](https://user-images.githubusercontent.com/1350297/136318541-4709231b-c92c-4280-94ce-95c3019f996b.gif)

**Comment by mcevoyandy** [comment]
Let me know if this did not resolve your issue and I'll reopen the issue.
